### ISSUE TITLE
Update to support TEP-0100: Embedded TaskRuns and Runs Status in PipelineRuns

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#2340]
[TEP-0100](https://github.com/tektoncd/community/blob/main/teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md) proposes changes to `PipelineRun` Status to reduce the amount of information stored about the status of `TaskRun`s and `Run`s to improve performance, reduce memory bloat and improve extensibility. See https://github.com/tektoncd/pipeline/issues/3140 and the [TEP](https://github.com/tektoncd/community/blob/main/teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md) for background information, details on motivation, and implementation.

The Dashboard currently uses `PipelineRun.status.taskRuns` in a number of places, but once the `embedded-status` flag is switched to `minimal` (will be default ~9 months from now) the Dashboard will no longer be able to use this data and will have to retrieve it by other means / from other sources.

Users can opt in to this new behaviour at any point so the Dashboard should be updated soon to start adding support, or at least ensuring it doesn't completely break the UI.

# TODO

- [ ] Identify places the Dashboard currently uses `PipelineRun.status.taskRuns`
  - Some of these are currently used as a fallback if the TaskRun resource has been deleted from the cluster and shouldn't cause any issues
- [ ] Identify the remaining uses that need attention, e.g. warning `StatusIcon` on `PipelineRuns` page
- [ ] Update code to retrieve the required data from other sources or remove the affected functionality
  - [ ] What is the impact of removing any affected functionality? Are there alternatives?

# NOTE
We should review this in more detail once the PIpelineRuns page design updates are implemented (finalising design 2022/04 and implementing in early 2022/05) as that may simplify (or potentially remove) some of the currently affected code.

**Comment by abayer** [comment]
This is a dependency of https://github.com/tektoncd/pipeline/issues/4954.

The new `embedded-status` feature flag, with `full` as the default value, is in Pipeline v0.35.0 and later.

**Comment by AlanGreene** [comment]
This is done and has been included in nightly builds for about a week. It will be included in the next Dashboard release (v0.28.0) next week.
